### PR TITLE
Make tokio optional

### PR DESCRIPTION
**Pull request by jguhlin**
Would you be willing to accept this (or similar) PR? I use bytelines pretty extensively but rarely use tokio, and this cuts down on the dependency tree by hiding it behind a "tokio" feature flag.

No worries either way, cheers.

### CODE REVIEW

**Comment by nickelc** [comment]
This can be further optimized by using only the `futures-util` crate.
```rust
use futures_util::stream::{self, Stream};
```

```toml
[dependencies]
futures-util = { default-features = false }
```

**Comment by whitfin** [comment]
@jguhlin hi! 

So sorry for taking so long to get to this, but happy to merge this in. All looks good, just wanted to double check you're happy with it? Would appreciate if you can add a note to the Tokio part of the README about now needing an option.

Edit: if I don't hear back, I'll circle back soon as get it merged in anyway - I see there's some downstream crates this could be useful for too.

**Comment by whitfin** [comment]
I'm going to merge this and get it released, but `tokio` will be enabled by default for the moment. I'm going to follow up (hopefully) soon with modules for the other runtimes rather than just Tokio. At this point I'll major bump, and make `std` the only default feature: https://github.com/whitfin/bytelines/issues/9

Thank you for your help everyone!

**Comment by jguhlin** [comment]
Apologies, I was out of the office until today and taking a break with bg3. I'm happy with it and thanks for pushing the update out!

**Pull request merged**
